AWSTemplateFormatVersion: '2010-09-09'
Description: 'Fase 4b: Bastion Host publico para acceso administrativo controlado'

Parameters:
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64'
    Description: AMI Amazon Linux 2023 mas reciente
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: vockey
    Description: Key pair existente para conectarse por SSH al bastion
  SSHLocation:
    Type: String
    Default: 0.0.0.0/0
    Description: CIDR autorizado para SSH. Para produccion usar tu IP publica con /32.

Resources:
  BastionSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permitir SSH controlado hacia el Bastion Host
      VpcId: !ImportValue Ecommerce-VPC-ID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHLocation
      Tags:
        - Key: Name
          Value: Ecommerce-Bastion-SG
        - Key: Project
          Value: Ecommerce-AWS-IAC

  BastionLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: !Ref LatestAmiId
        InstanceType: t2.micro
        KeyName: !Ref KeyName
        SecurityGroupIds:
          - !Ref BastionSecurityGroup

  BastionAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: Ecommerce-Bastion-ASG
      VPCZoneIdentifier:
        - !Select [ 0, !Split [ ",", !ImportValue Ecommerce-Public-Subnets ] ]
      LaunchTemplate:
        LaunchTemplateId: !Ref BastionLaunchTemplate
        Version: !GetAtt BastionLaunchTemplate.LatestVersionNumber
      MinSize: '1'
      MaxSize: '1'
      DesiredCapacity: '1'
      Tags:
        - Key: Name
          Value: Ecommerce-Bastion
          PropagateAtLaunch: true
        - Key: Project
          Value: Ecommerce-AWS-IAC
          PropagateAtLaunch: true

Outputs:
  BastionAutoScalingGroupName:
    Description: Nombre del Auto Scaling Group que mantiene una instancia Bastion
    Value: !Ref BastionAutoScalingGroup
    Export:
      Name: Ecommerce-Bastion-ASG-Name
  BastionSecurityGroupId:
    Description: Security Group del Bastion Host
    Value: !GetAtt BastionSecurityGroup.GroupId
    Export:
      Name: Ecommerce-Bastion-SG-ID
