AWSTemplateFormatVersion: '2010-09-09'
Description: 'Fase 3: Capa de Datos - RDS MySQL privado'

Parameters:
  DBName:
    Type: String
    Default: ecommercedb
  DBUsername:
    Type: String
    Default: dbadmin
  DBPassword:
    Type: String
    NoEcho: true
    MinLength: 8

Resources:
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permitir MySQL solo desde las instancias de la aplicacion
      VpcId: !ImportValue Ecommerce-VPC-ID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !ImportValue Ecommerce-App-SG-ID
      Tags:
        - Key: Name
          Value: Ecommerce-DB-SG

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Grupo de subredes privadas para la DB
      SubnetIds: !Split [ ",", !ImportValue Ecommerce-Private-Subnets ]
      Tags:
        - Key: Name
          Value: Ecommerce-DB-Subnet-Group

  EcommerceDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref DBName
      AllocatedStorage: '20'
      DBInstanceClass: db.t3.micro
      Engine: mysql
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - !GetAtt DBSecurityGroup.GroupId
      PubliclyAccessible: false
      BackupRetentionPeriod: 1
      DeletionProtection: false
      Tags:
        - Key: Name
          Value: Ecommerce-Database

Outputs:
  DBName:
    Description: Nombre de la base de datos usada por la aplicacion
    Value: !Ref DBName
    Export:
      Name: Ecommerce-DB-Name
  DBUsername:
    Description: Usuario maestro de la base de datos
    Value: !Ref DBUsername
    Export:
      Name: Ecommerce-DB-Username
  DBEndpoint:
    Description: URL de conexion para la aplicacion
    Value: !GetAtt EcommerceDB.Endpoint.Address
    Export:
      Name: Ecommerce-DB-Endpoint
  DBSecurityGroupId:
    Description: Security Group privado de RDS
    Value: !GetAtt DBSecurityGroup.GroupId
    Export:
      Name: Ecommerce-DB-SG-ID
